"""add professional column

Revision ID: 0d3e604316a8
Revises: 82a4b3b05d0f
Create Date: 2025-08-14 12:22:55.499578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3e604316a8'
down_revision: Union[str, Sequence[str], None] = '82a4b3b05d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Internships', sa.Column('professional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Internships', 'professional')
    # ### end Alembic commands ###
