"""Create internships table

Revision ID: 5b075c2321aa
Revises: 
Create Date: 2025-08-14 09:38:38.857326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b075c2321aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('cv_path', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Internships_id'), 'Internships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Internships_id'), table_name='Internships')
    op.drop_table('Internships')
    # ### end Alembic commands ###
