"""Add application column to Internships

Revision ID: 82a4b3b05d0f
Revises: 5b075c2321aa
Create Date: 2025-08-14 09:59:20.863476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a4b3b05d0f'
down_revision: Union[str, Sequence[str], None] = '5b075c2321aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Internships', sa.Column('application', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Internships', 'application')
    # ### end Alembic commands ###
